# Generated by Django 3.0.6 on 2020-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(default='sale', max_length=50)),
                ('product_brand', models.CharField(default='', max_length=50)),
                ('product_description', models.CharField(max_length=300)),
                ('product_price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
