# Generated by Django 3.0.6 on 2020-08-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiFeyZone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_discount',
            field=models.IntegerField(default=30),
        ),
    ]
