# Generated by Django 3.0.6 on 2020-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiFeyZone', '0002_products_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_email', models.CharField(max_length=50)),
                ('person_product', models.IntegerField()),
            ],
        ),
    ]
